
SELECT DISTINCT

A.NU_ANO_MES_RFRN,
A.DT_PRMR_ATVC,
A.DATA_NF_KEY,
A.DATA_NF,
A.NOTA_FISCAL,
A.ORDEM_VEND,
A.CPF_CNPJ,
A.SEGMENTO,
A.CANAL_FATURAMENTO,
A.FABRICANTE,
A.DESCRICAO_MATERIAL,
A.CLASSIF_CATEGORIA,
A.CATEGORIA,
A.CATEGORIA_PLANEJAMENTO,
A.SUBCATEGORIA_GERENCIAL,
A.DS_LINHA_PRODUTO,
A.NOME_COMERCIAL,
A.CD_CRDN,
A.GA,
A.GV,
A.ID_DDD_PDV,
A.DS_LOGN_VNDD,
D.NO_ATND,
A.DS_TIPO_MVMT_LNHA,
A.DS_TIPO_MVMT_LNHA_AGPR,
A.DS_SGMT_CLNT,
A.KEY_ATTACH_SMART,
B.FLAG_ATTACH_ELETRONICOS,
C.FLAG_ATTACH_ESSENCIAIS,
B.CATEGORIA AS CATEGORIA_TT,
B.SUBCATEGORIA_GERENCIAL AS SUBCATEGORIA_GERENCIAL_TT,
B.DS_LINHA_PRODUTO AS DS_LINHA_PRODUTO_TT,

A.QT_ATVC_SBSD


FROM VPV_RGNL_NE.VVIC_SUBSIDIO_ATTACH_TERMINAIS A
LEFT JOIN VPV_RGNL_NE.VVIC_SUBSIDIO_ATTACH_ELETRONICOS B ON A.KEY_ATTACH_SMART = B.KEY_ATTACH_ELETRONICOS
LEFT JOIN VPV_RGNL_NE.VVIC_SUBSIDIO_ATTACH_ESSENCIAIS C ON A.KEY_ATTACH_SMART = C.KEY_ATTACH_ESSENCIAIS
LEFT JOIN VPV_PRD_DM.TVIC_DIM_ATND D ON A.DS_LOGN_VNDD = D.CD_ADBA_ATND

WHERE A.NU_ANO_MES_RFRN >= '202603' 
AND A.CANAL_FATURAMENTO IN ('LOJAS PROPRIAS','REVENDA')
AND A.FABRICANTE NOT IN ('LG','INFINIX')

ORDER BY DT_PRMR_ATVC;

