--CREATE OR REPLACE VIEW BSC_FAT_MOVEL AS

SELECT

NU_ANO_MES_RFRN,
TO_CHAR(TO_DATE(ID_DIA,'YYYY-MM-DD'),'DD/MM/YYYY') AS DATA,
ID_DIA,
SG_RGNL_BSC,
TRANSLATE (UPPER (DS_TRRT_BSC),'ÁÇÉÍÓÚÀÈÌÒÙÂÊÎÔÛÃÕËÜ','ACEIOUAEIOUAEIOUAOEU') AS DS_TRRT_BSC,
SG_UF,
NO_CDDE,
ID_DDD_BSC,
DS_CNL_NVL_5,
DS_CNL_NVL_1,
CD_CRDN,
DS_NTZA_PRDT,
DS_SGMT_PRDT,
DS_TCNL,

CASE

WHEN DS_INDC_CMRC = 'ALTA' THEN 'ALTA'
WHEN DS_INDC_CMRC = 'Migração Terminal Controle PF para Terminal Pós PF' THEN 'MIGRACAO CONTROLE-POS'
WHEN DS_INDC_CMRC = 'Migração Terminal Pré para Terminal Controle PF' THEN 'MIGRACAO PRE-CONTROLE'
WHEN DS_INDC_CMRC = 'Migração Terminal Pré para Terminal Pós PF' THEN 'MIGRACAO PRE-POS'
WHEN DS_INDC_CMRC = 'UPGRADE LINHA (BRUTO-DESCONTO)' THEN 'UPGRADE'

ELSE DS_INDC_CMRC END AS DS_INDC_CMRC_SHORT,

DS_INDC_CMRC,

SUM (QT_FSCO) AS QT_FSCO,
SUM (VL_RCTA_FACE) AS VL_RCTA_FACE

FROM VPV_SDBX_PLNJ.VVIC_FLT_FSCO_VLRD_MNCO_GRCL_1 
WHERE NU_ANO_MES_RFRN >= '202601'         
AND DS_INDC_CMRC IN 
('ALTA',
'UPGRADE LINHA (BRUTO-DESCONTO)',
'Migração Terminal Controle PF para Terminal Pós PF',
'Migração Terminal Pré para Terminal Controle PF',
'Migração Terminal Pré para Terminal Pós PF')

AND DS_CTGR_PRDT NOT IN 'DEPENDENTE GRÁTIS' 
AND DS_SGMT_PRDT IN ('CONTROLE', 'PÓS PURO')
AND DS_CNL_NVL_5 = 'PRESENCIAIS'

GROUP BY

NU_ANO_MES_RFRN,
ID_DIA,
ID_DIA,
SG_RGNL_BSC,
DS_TRRT_BSC,
SG_UF,
NO_CDDE,
ID_DDD_BSC,
DS_CNL_NVL_5,
DS_CNL_NVL_1,
CD_CRDN,
DS_NTZA_PRDT,
DS_SGMT_PRDT,
DS_TCNL,
DS_INDC_CMRC

ORDER BY ID_DIA DESC    