--CREATE OR REPLACE VIEW BSC_FAT_FIXA_B2B AS

SELECT

NU_ANO_MES_RFRN,
TO_CHAR(TO_DATE(ID_DIA,'YYYY-MM-DD'),'DD/MM/YYYY') AS DATA,
ID_DIA,
SG_RGNL_BSC,
TRANSLATE (UPPER (DS_TRRT_BSC),'ÁÇÉÍÓÚÀÈÌÒÙÂÊÎÔÛÃÕËÜ','ACEIOUAEIOUAEIOUAOEU') AS DS_TRRT_BSC,
SG_UF,
NO_CDDE,
ID_DDD_BSC,
DS_CNL_NVL_5,
DS_CNL_NVL_1,
CD_CRDN,
DS_CRTR,
DS_NTZA_PRDT,
DS_SGMT_PRDT,
DS_TCNL,

CASE

WHEN DS_INDC_CMRC = 'VENDAS BRUTAS' THEN 'VENDAS LIQUIDAS'
WHEN DS_INDC_CMRC = 'CANCELAMENTOS' THEN 'VENDAS LIQUIDAS'
WHEN DS_INDC_CMRC = 'MIGRACAO BRUTA FTTC - FTTH' THEN 'MIGRACAO'
WHEN DS_INDC_CMRC = 'MIGRACAO BRUTA MOTF FTTC - FTTH' THEN 'MIGRACAO'
WHEN DS_INDC_CMRC = 'MIGRACAO BRUTA MOTF XDSL - FTTH' THEN 'MIGRACAO'
WHEN DS_INDC_CMRC = 'MIGRACAO BRUTA XDSL - FTTH' THEN 'MIGRACAO'
WHEN DS_INDC_CMRC = 'MIGRACAO CANCELADA FTTC - FTTH' THEN 'MIGRACAO'
WHEN DS_INDC_CMRC = 'MIGRACAO CANCELADA MOTF FTTC - FTTH' THEN 'MIGRACAO'
WHEN DS_INDC_CMRC = 'MIGRACAO CANCELADA XDSL - FTTH' THEN 'MIGRACAO'
WHEN DS_INDC_CMRC = 'MOTF UPGRADE (BRUTO-DESCONTO)H' THEN 'UPGRADE'
WHEN DS_INDC_CMRC = 'NEXT UPGRADE (BRUTO-DESCONTO)' THEN 'UPGRADE'
WHEN DS_INDC_CMRC = 'UPGRADE (BRUTO-DESCONTO-IMPOSTO)' THEN 'UPGRADE'
ELSE DS_INDC_CMRC END AS DS_INDC_CMRC,

DS_INDC_CMRC,

SUM (QT_FSCO) AS QT_FSCO,
SUM (VL_RCTA_FACE) + SUM(VL_TRCO_BRTO_BNDL) AS VL_RCTA

FROM VPV_SDBX_PLNJ.VVIC_FLT_FSCO_VLRD_MNCO_FIXA

WHERE
NU_ANO_MES_RFRN >= '202601'
AND DS_CRTR = 'B2B'
AND DS_TCNL IN ('IPTV', 'FTTH')
AND DS_CNL_NVL_5 = 'PRESENCIAIS'
AND DS_INDC_CMRC IN
                              ('MIGRACAO BRUTA DTH - IPTV',
                               'MIGRACAO BRUTA FTTC - FTTH',
                               'MIGRACAO BRUTA XDSL - FTTH',
                               'MIGRACAO CANCELADA DTH - IPTV',
                               'MIGRACAO CANCELADA FTTC - FTTH',
                               'MIGRACAO CANCELADA XDSL - FTTH',
                               'MIGRACAO BRUTA MOTF DTH - IPTV',
                               'MIGRACAO BRUTA MOTF FTTC - FTTH',
                               'MIGRACAO BRUTA MOTF XDSL - FTTH',
                               'MIGRACAO CANCELADA MOTF DTH - IPTV',
                               'MIGRACAO CANCELADA MOTF FTTC - FTTH',
                               'MIGRACAO CANCELADA MOTF XDSL - FTTH',
                               'VENDAS BRUTAS',
                               'CANCELAMENTOS',
                               'MOTF UPGRADE (BRUTO-DESCONTO)',
                               'NEXT UPGRADE (BRUTO-DESCONTO)',
                               'UPGRADE (BRUTO-DESCONTO-IMPOSTO)'
                              )

GROUP BY

NU_ANO_MES_RFRN,
ID_DIA,
ID_DIA,
SG_RGNL_BSC,
DS_TRRT_BSC,
SG_UF,
NO_CDDE,
ID_DDD_BSC,
DS_CNL_NVL_5,
DS_CNL_NVL_1,
CD_CRDN,
DS_CRTR,
DS_NTZA_PRDT,
DS_SGMT_PRDT,
DS_TCNL,
DS_INDC_CMRC

ORDER BY ID_DIA DESC                              