--CREATE OR REPLACE VIEW BSC_FAT_MOVEL_B2B AS

SELECT
NU_ANO_MES_RFRN,
TO_CHAR(TO_DATE(ID_DIA,'YYYY-MM-DD'),'DD/MM/YYYY') AS DATA,
ID_DIA,
SG_RGNL_BSC,
TRANSLATE (UPPER (DS_TRRT_BSC),'ÁÇÉÍÓÚÀÈÌÒÙÂÊÎÔÛÃÕËÜ','ACEIOUAEIOUAEIOUAOEU') AS DS_TRRT_BSC,
SG_UF,
NO_CDDE,
ID_DDD_BSC,
DS_CNL_NVL_5,
DS_CNL_NVL_1,
CD_CRDN,
DS_NTZA_PRDT,
DS_SGMT_PRDT,
DS_TCNL,
DS_INDC_CMRC,
SUM (QT_FSCO) AS QT_FSCO,
SUM (VL_RCTA_FACE) AS VL_RCTA_FACE

FROM SVC_BIOVD.VVIC_FLT_FSCO_VLRD_GRCL_B2B

WHERE DS_CNL_NVL_5 = 'PRESENCIAIS'
AND NU_ANO_MES_RFRN >= '202601'
AND DS_CTGR_PRDT = 'TITULAR'
AND DS_CNL_NVL_1 IN ('LOJAS PROPRIAS','REVENDA')   
AND DS_SGMT_PRDT = 'PÓS PURO'
  
GROUP BY
NU_ANO_MES_RFRN,
ID_DIA,
ID_DIA,
SG_RGNL_BSC,
DS_TRRT_BSC,
SG_UF,
NO_CDDE,
ID_DDD_BSC,
DS_CNL_NVL_5,
DS_CNL_NVL_1,
CD_CRDN,
DS_NTZA_PRDT,
DS_SGMT_PRDT,
DS_TCNL,
DS_INDC_CMRC
  
order by ID_DIA desc