--CREATE OR REPLACE VIEW BSC_FAT_CES AS  
  
SELECT DISTINCT

NU_ANO_MES_RFRN,
DATA_NF,
SG_RGNL,
TRANSLATE (UPPER (SG_TRRT_PDV),'ÁÇÉÍÓÚÀÈÌÒÙÂÊÎÔÛÃÕËÜ','ACEIOUAEIOUAEIOUAOEU') AS SG_TRRT_PDV,
ID_DDD_PDV,
ID_UF_PDV,
CANAL_FATURAMENTO,
CD_CRDN,
TRANSLATE (UPPER (CLASSIF_CATEGORIA),'ÁÇÉÍÓÚÀÈÌÒÙÂÊÎÔÛÃÕËÜ','ACEIOUAEIOUAEIOUAOEU') AS CLASSIF_CATEGORIA,

SUM (QT_ATVC_SBSD) AS QT_ATVC_SBSD,
SUM (VL_VNDA_APARELHO) AS VL_VNDA_APARELHO

FROM VPV_SDBX_PLNJ.VVIC_ODS_BSC_TRMN_MES

WHERE NU_ANO_MES_RFRN >= '202601'
AND CANAL_FATURAMENTO IN ('LOJAS PROPRIAS','REVENDA')


GROUP BY

NU_ANO_MES_RFRN,
DATA_NF,
SG_RGNL,
SG_TRRT_PDV,
ID_DDD_PDV,
ID_UF_PDV,
CANAL_FATURAMENTO,
CD_CRDN,
CLASSIF_CATEGORIA

UNION ALL

--CREATE OR REPLACE VIEW BSC_DIM_CES AS  
  
SELECT DISTINCT

NU_ANO_MES_RFRN,
DATA_NF,
SG_RGNL,
TRANSLATE (UPPER (SG_TRRT_PDV),'ÁÇÉÍÓÚÀÈÌÒÙÂÊÎÔÛÃÕËÜ','ACEIOUAEIOUAEIOUAOEU') AS SG_TRRT_PDV,
ID_DDD_PDV,
ID_UF_PDV,
CANAL_FATURAMENTO,
CD_CRDN,
TRANSLATE (UPPER (CLASSIF_CATEGORIA),'ÁÇÉÍÓÚÀÈÌÒÙÂÊÎÔÛÃÕËÜ','ACEIOUAEIOUAEIOUAOEU') AS CLASSIF_CATEGORIA,

SUM (QT_ATVC_SBSD) AS QT_ATVC_SBSD,
SUM (VL_VNDA_APARELHO) AS VL_VNDA_APARELHO

FROM VPV_SDBX_PLNJ.VVIC_ODS_BSC_TRMN_DIA

WHERE NU_ANO_MES_RFRN >= '202601'
AND CANAL_FATURAMENTO IN ('LOJAS PROPRIAS','REVENDA')


GROUP BY

NU_ANO_MES_RFRN,
DATA_NF,
SG_RGNL,
SG_TRRT_PDV,
ID_DDD_PDV,
ID_UF_PDV,
CANAL_FATURAMENTO,
CD_CRDN,
CLASSIF_CATEGORIA

ORDER BY DATA_NF DESC