--CREATE OR REPLACE VIEW BSC_FAT_MOVEL_REC_M0 AS

SELECT

NU_ANO_MES_RFRN,
TO_CHAR(TO_DATE(ID_DIA,'YYYY-MM-DD'),'DD/MM/YYYY') AS DATA,
ID_DIA,
SG_RGNL_BSC,
TRANSLATE (UPPER (DS_TRRT_BSC),'ÁÇÉÍÓÚÀÈÌÒÙÂÊÎÔÛÃÕËÜ','ACEIOUAEIOUAEIOUAOEU') AS DS_TRRT_BSC,
SG_UF,
ID_DDD_BSC,
DS_CNL_NVL_5,
DS_CNL_NVL_1,
DS_NTZA_PRDT,
DS_SGMT_PRDT,
DS_TCNL,

DS_INDC_CMRC,

SUM (QT_FSCO) AS QT_FSCO

from VPV_SDBX_PLNJ.VVIC_FLT_FSCO_VLRD_MNCO_GRCL_3

WHERE NU_ANO_MES_RFRN >= '202601' 
AND DS_CNL_NVL_5 = 'PRESENCIAIS'
AND DS_INDC_CMRC = 'ALTA M0'

GROUP BY

NU_ANO_MES_RFRN,
ID_DIA,
ID_DIA,
SG_RGNL_BSC,
DS_TRRT_BSC,
SG_UF,
ID_DDD_BSC,
DS_CNL_NVL_5,
DS_CNL_NVL_1,
DS_NTZA_PRDT,
DS_SGMT_PRDT,
DS_TCNL,
DS_INDC_CMRC

ORDER BY ID_DIA DESC  